CREATE TABLE `projeto`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `endereco` VARCHAR(200) NULL,
  `bairro` VARCHAR(200) NULL,
  `cidade` VARCHAR(200) NULL,
  `estado` VARCHAR(200) NULL,
  `cep` VARCHAR(10) NULL,
  `documento` VARCHAR(45) NULL,
  `email` VARCHAR(200) NULL,
  `senha` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `dtcad` DATETIME NULL,
  `delet` VARCHAR(1) NULL DEFAULT ' ',
  PRIMARY KEY (`id`));
